; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
board_build.filesystem = littlefs
framework = arduino
monitor_port = COM40
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

;**********************************************************************
; START Customise the settings here!
;
; VARIABLE=value (no spaces)
;**********************************************************************
	; ip addresses:
	; 192.168.97.62 is "master (8-relay)"
	; 192.168.97.63 is "LDG Antenna Switch (8 Relay)"
	; 192.168.97.64 is "FLEX Control"
	; 192.168.97.65 is
	; 192.168.97.66 is "LF / VHF-UHF (8-relay)"
	; 192.168.97.67 is 
	; 192.168.97.68 is "Eastern Tower Band Selector (16-relay)"
	; 192.168.97.69 is "Western Tower Band Selector (16-relay)"

build_flags = 
	-D IP4=64				; the last number in the IP address. 65 = xx.xx.xx.65

;**********************************************************************
; END Customise the settings here!
;
; VARIABLE=value (no spaces)
;**********************************************************************

[env:esp8266_serial]
platform = espressif8266
board = esp12e
board_build.partitions = partition.csv
lib_deps = 
	me-no-dev/ESPAsyncTCP@^1.2.2
	me-no-dev/ESP Async WebServer@^1.2.3
	bblanchon/ArduinoJson@^6.21.2

extends = common
upload_port = COM40
upload_speed = 1500000

[env:esp8266_ota]
platform = espressif8266
board = esp12e
board_build.partitions = partition.csv
lib_deps = 
	me-no-dev/ESPAsyncTCP@^1.2.2
	me-no-dev/ESP Async WebServer@^1.2.3
	bblanchon/ArduinoJson@^6.21.2

extends = common
upload_protocol = espota
upload_port = 192.168.97.64

[env:esp32_serial]
platform = espressif32
board = espino32
board_build.partitions = default.csv	; 4MB - 0x140000 app, 0x160000 spiffs
extends = common
extra_scripts = pre:scripts/pio_custom_targets.py
upload_port = COM40
upload_speed = 1500000
lib_deps = 
	me-no-dev/AsyncTCP@^1.1.1
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	bblanchon/ArduinoJson@^6.21.2

[env:esp32_ota]
platform = espressif32
board = espino32
board_build.partitions = default.csv	; 4MB - 0x140000 app, 0x160000 spiffs
extends = common
extra_scripts = pre:scripts/pio_custom_targets.py
upload_protocol = espota
upload_port = relay-board.local
build_flags =
	${common.build_flags}
	-D OTA_HOSTNAME=\"relay-board\"
lib_deps = 
	me-no-dev/AsyncTCP@^1.1.1
	https://github.com/me-no-dev/ESPAsyncWebServer.git
	bblanchon/ArduinoJson@^6.21.2

