; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]
board_build.filesystem = littlefs
framework = arduino
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0

[common_esp8266]
extends = common
build_flags = -Wno-deprecated-declarations

[env:esp8266_serial]
platform = espressif8266
board = esp12e
board_build.partitions = partition.csv
extra_scripts = pre:scripts/pio_custom_targets.py
lib_deps =
	me-no-dev/ESPAsyncWebServer@^1.2.3
	me-no-dev/ESPAsyncTCP@^1.2.2
	bblanchon/ArduinoJson@^7.2.2
extends = common_esp8266
monitor_port = COM4
upload_port = COM4
upload_speed = 1500000

[env:esp8266_ota]
platform = espressif8266
board = esp12e
board_build.partitions = partition.csv
extra_scripts = pre:scripts/pio_custom_targets.py
lib_deps =
	me-no-dev/ESPAsyncWebServer@^1.2.3
	me-no-dev/ESPAsyncTCP@^1.2.2
	bblanchon/ArduinoJson@^7.2.2
extends = common_esp8266
upload_protocol = espota
upload_port = 192.168.2.217

[env:esp32_serial]
platform = espressif32
board = espino32
board_build.partitions = default.csv
extends = common
extra_scripts = pre:scripts/pio_custom_targets.py
monitor_port = COM3
upload_port = COM3
upload_speed = 1500000
lib_deps =
	esp32async/ESPAsyncWebServer@^3.11.2
	bblanchon/ArduinoJson@^7.2.2

[env:esp32_ota]
platform = espressif32
board = espino32
board_build.partitions = default.csv
extends = common
extra_scripts = pre:scripts/pio_custom_targets.py
upload_protocol = espota
upload_port = 192.168.2.195
lib_deps =
	esp32async/ESPAsyncWebServer@^3.11.2
	bblanchon/ArduinoJson@^7.2.2
